apiVersion: v2
description: The easy, open source way for everyone in your company to ask questions and learn from data.
name: metabase
type: application
version: 1.8.0
appVersion: v0.53.4.3
home: https://github.com/rdomenzain/charts/tree/main/charts/metabase
icon: http://www.metabase.com/images/logo.svg
maintainers:
  - name: rdomenzain
    url: https://github.com/rdomenzain/
sources:
  - https://github.com/rdomenzain/helm-chart/tree/main/charts/metabase
